- name: Installing MySQL
  ansible.builtin.import_role:
    name: common
    tasks_from: install-mysql

- name: Enabling and Starting mysqld service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: change the default root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1