- name: Install golang
  ansible.builtin.import_role:
    name: common
    tasks_from: install-golang

- name: "set-up {{component}} application"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Installing Dependencies
  ansible.builtin.shell: |
    go mod init dispatch
    go get
    go build
  args:
    chdir: /app

- name: Set-Up Systemd service
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-service