- name: Copying mongo.repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Enable and Starting mongod service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes