- name: Installing Redis Repo File
  ansible.builtin.yum: 
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: yes

- name: Enable Redis 6.2 package
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Installing redis
  ansible.builtin.yum: 
    name: redis
    state: installed